feat: ,demo-mode works when the laptop lid is closed

diff --git a/bin/,demo-mode b/bin/,demo-mode
--- a/bin/,demo-mode
+++ b/bin/,demo-mode
@@ -20,5 +20,25 @@ else
   exit 1
 fi
 
-# displayplacer list | rg '^displayplacer "'
-displayplacer "id:E7E732C7-9072-4BF4-8D39-6A15A280ED75 res:$res hz:75 color_depth:8 enabled:true scaling:$scaling origin:(0,0) degree:0" "id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:1168x755 hz:120 color_depth:8 enabled:true scaling:on origin:(-1168,0) degree:0"
+display_configs=$(displayplacer list)
+
+if [[ $? -ne 0 ]]; then
+  echo "Error: Failed to get display configurations."
+  exit 1
+fi
+
+laptop_display_config=$(echo "$display_configs" | grep "id:37D8832A-2D66-02CA-B9F7-8F30A301B230")
+
+main_display_update="id:E7E732C7-9072-4BF4-8D39-6A15A280ED75 res:$res hz:75 color_depth:8 enabled:true scaling:$scaling origin:(0,0) degree:0"
+laptop_display_update="id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:1168x755 hz:120 color_depth:8 enabled:true scaling:on origin:(-1168,0) degree:0"
+
+if [[ -n "$laptop_display_config" ]]; then
+  displayplacer "$main_display_update" "$laptop_display_update"
+else
+  displayplacer "$main_display_update"
+fi
+
+if [[ $? -ne 0 ]]; then
+  echo "Error: Failed to update display configurations."
+  exit 1
+fi
